title: Rainbow run
hero_image: images/banner.png
description: Create a track for a ball to roll along. Add obstacles and a goal for the ball to reach.
meta_title: Rainbow run
meta_description: Create a track for a ball to roll along. Add obstacles and a goal for the ball to reach.
keywords:
- unity
- ball
- marble
- 3d
- game
version: 1
listed: false
copyedit: false
last_tested: "2023-06-13"
steps:
  - title: You will make
  - title: Build the track
  - title: Create a ball
    completion:
      - engaged
  - title: Control the camera
  - title: Control the ball
  - title: Add a reset button
  - title: Add moving obstacles
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade
  - title: What next?
