title: Rainbow run
hero_image: images/banner.png
description: Create a track for a ball to roll along. Add obstacles and a goal for the ball to reach.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Build the track
  - title: Create a ball
    completion:
      - engaged
  - title: Control the camera
  - title: Control the ball
  - title: Add a reset button
  - title: Add moving obstacles
    completion:
      - internal
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Upgrade
  - title: What next?
